[package]

# Semantic Versioning is used: https://semver.org/
version = "1.0.1"

# Description
category = "isaaclab"
readme  = "README.md"

title = "Isaac Lab Mimic"
author = "Isaac Lab Project Developers"
maintainer = "Isaac Lab Project Developers"
description="Mimic for Isaac Lab"
repository = "https://github.com/isaac-sim/IsaacLab.git"
keywords = ["extension", "template", "isaaclab"]

[dependencies]
"omni.isaac.lab" = {}
"omni.isaac.lab_assets" = {}
"omni.isaac.lab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "omni.isaac.lab_mimic"

[isaaclab_settings]
