# Reference: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/ppo.yml#L32
seed: 42



n_timesteps: !!float 1e6
policy: 'CnnPolicy'
batch_size: 128
n_steps: 128
gamma: 0.99
gae_lambda: 0.95
n_epochs: 100
ent_coef: 0.01
vf_coef: 1
learning_rate: lin_1e-4
use_sde: True
clip_range: 0.2
policy_kwargs: "dict(log_std_init=-2,
                      ortho_init=False,
                      activation_fn=nn.GELU,
                      net_arch=dict(pi=[256], vf=[256]),
                      normalize_images=False,
                      )"
max_grad_norm: 1.0
device: "cuda:0"
