[package]
# Semantic Versioning is used: https://semver.org/
version = "0.1.2"

# Description
title =  "ORBIT Assets"
description="Extension containing configuration instances of different assets and sensors"
readme  = "docs/README.md"
repository = "https://github.com/NVIDIA-Omniverse/Orbit"
category = "robotics"
keywords = ["kit", "robotics", "assets", "orbit"]

[dependencies]
"omni.isaac.orbit" = {}

# Main python module this extension provides.
[[python.module]]
name = "omni.isaac.orbit_assets"
