[package]

# Note: Semantic Versioning is used: https://semver.org/
version = "0.17.13"

# Description
title = "Isaac Lab framework for Robot Learning"
description="Extension providing main framework interfaces and abstractions for robot learning."
readme  = "docs/README.md"
repository = "https://github.com/isaac-sim/IsaacLab"
category = "robotics"
keywords = ["kit", "robotics", "learning", "ai"]

[dependencies]
"omni.isaac.core" = {}
"omni.replicator.core" = {}

[[python.module]]
name = "omni.isaac.lab"
